services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: devops_demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ../backend
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: devops_demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    ports:
      - '4000:4000'
    volumes:
      - ../backend:/usr/src/app

  frontend:
    build: ../frontend
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ../frontend:/usr/src/app

volumes:
  pgdata:
